<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-10-09 07:11
=======
# Generated by Django 3.2.7 on 2021-10-09 06:02
>>>>>>> 899b45b3c1bffe4d77a6ddd3c40d9d1280a2069a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('color_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('task_count', models.IntegerField(default=0)),
                ('is_notification', models.BooleanField(default=True)),
                ('task_limit', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=1000, null=True)),
                ('url', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=10)),
                ('next_display_date', models.DateField()),
                ('display_times', models.IntegerField(default=1)),
                ('consecutive_times', models.IntegerField(default=0)),
                ('is_update', models.BooleanField(default=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feedback', models.IntegerField(default=1)),
                ('number_of_tasks', models.IntegerField(default=0)),
                ('execution_tasks', models.IntegerField(default=0)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
