# Generated by Django 3.2.7 on 2021-10-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='display_task',
        ),
        migrations.AlterField(
            model_name='setting',
            name='task_limit',
            field=models.IntegerField(default=100),
        ),
    ]
