# Generated by Django 3.2.7 on 2021-10-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task_limit',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
