# Generated by Django 3.2.7 on 2021-10-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211020_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Profile',
        ),
    ]
