# Generated by Django 3.2.7 on 2021-10-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211011_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='display_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=100),
        ),
    ]
