# Generated by Django 3.2.7 on 2021-10-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211011_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category_id',
        ),
        migrations.CreateModel(
            name='TaskCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(through='app.TaskCategoryRelation', to='app.Category'),
        ),
    ]
