# Generated by Django 3.2.7 on 2021-10-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211011_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update_time',
            field=models.IntegerField(default=0),
        ),
    ]
