# Generated by Django 3.2.7 on 2021-10-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_task_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='update_time',
        ),
        migrations.AddField(
            model_name='user',
            name='update_time',
            field=models.IntegerField(default=0),
        ),
    ]
