# Generated by Django 3.2.7 on 2021-10-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211013_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
