# Generated by Django 3.2.7 on 2021-10-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='display_task',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='update_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
